services:
  - type: web
    name: realtime-conversational-agent-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app"
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: realtime-conversational-agent
      - key: PYTHON_VERSION
        value: "3.11.0"
        
  - type: web
    name: realtime-conversational-agent-client
    plan: free
    env: static
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: "./client/out"
    envVars:
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        fromService:
          type: web
          name: realtime-conversational-agent-server
          property: url
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
